name: CI/CD for Spring Application

on:
  push:
    branches:
      - main  # Vous pouvez spécifier la branche que vous souhaitez surveiller ici

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code source
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: ubuntu-20.04 
        java-version: 11  # Spécifiez la version de Java appropriée

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test
